export const defaultRespawns = [
  { name: 'issavi', image: 'goanna.gif' },
  { name: 'ingol -3', image: 'carnivostrich.gif' },
  { name: 'secret library (ice area)', image: 'icecold_book.gif' },
  { name: 'secret library (fire area)', image: 'burning_book.gif' },
  { name: 'secret library (energy area)', image: 'energy_book.gif' },
  { name: 'wardragon -1', image: 'wardragon.gif' },
  { name: 'wardragon -2', image: 'wardragon.gif' },
  { name: 'Piolho -1', image: 'piolho.gif' },
  { name: 'Piolho -2', image: 'piolho2.gif' },
  { name: 'cobra', image: 'cobra_assassin.gif' },
  { name: 'cobra Bastion', image: 'cobra_assassin.gif' },
  { name: 'Rotten Esquerda', image: 'rotten_golem.gif' },
  { name: 'Rotten Direita', image: 'rotten_golem.gif' },
  { name: 'Furious Crater (Cloak)', image: 'cloak.gif' },
  { name: 'Dark Thais', image: 'manyfaces.gif' },
  { name: 'ebb and flow (fear)', image: 'bony.gif' },
  { name: 'Brachiodemon', image: 'brachiodemon.gif' },
  { name: 'Crystal Enigma Sul', image: 'mantosaurus.gif' },
  { name: 'Crystal Enigma Norte', image: 'mantosaurus.gif' },
  { name: 'Sparkling Pools Sul', image: 'gorerilla.gif' },
  { name: 'Sparkling Pools Norte', image: 'gorerilla.gif' },
  { name: 'Monster Graveyard', image: 'nighthunter.gif' },
  { name: 'Darklight Core', image: 'darklight.gif' },
  { name: 'Gloom Pillars', image: 'pillar.gif' },
  { name: 'Putrefactory', image: 'rotten_man.gif' },
  { name: 'Asura Mirror', image: 'asura.gif' },
  { name: 'Buried Cathedral -3', image: 'burster.gif' },
  { name: 'prison -3', image: 'prison.gif' },
]
