export const respawns = [
    {
      city: "Ankrahmun",
      spawns: [
        { code: "B3", name: "GS Tomb" },
        { code: "B4", name: "Hydra (Passage)" },
        { code: "B5", name: "Lion's Rock" },
        { code: "B6", name: "Mahrdis" },
        { code: "B7", name: "Oasis Tomb" },
        { code: "B8", name: "Peninsula Tomb" },
        { code: "B9", name: "Rahemons" },
        { code: "B10", name: "Stone Tomb" },
        { code: "B11", name: "Terramite" },
        { code: "B12", name: "Vashresamun" },
        { code: "B13", name: "Mother of Scarab Lair" },
        { code: "B14", name: "Gold Token" },
        { code: "B15", name: "Cobra Bastion (-1)" },
        { code: "B16", name: "Cobra Bastion (0 & +1 flask)" },
        { code: "B17", name: "Cobra Bastion (+1 after flask, +2, +3 & +4)" },
        { code: "B18", name: "Cobra Bastion (Mini Boss Fire)" },
        { code: "B19", name: "Cobra Bastion (Mini Boss Smoke)" },
        { code: "B20", name: "Cobra Bastion (0 and +1)" },
        { code: "B21", name: "Cobra Bastion (+2, +3 & +4)" },
        { code: "B22", name: "Cobra Bastion (+3 & +4)" }
      ]
    },
    {
      city: "Carlin",
      spawns: [
        { code: "C1", name: "Corym" },
        { code: "C2", name: "Demona" },
        { code: "C3", name: "Dragon" },
        { code: "C4", name: "Cults" },
        { code: "C5", name: "Secret Library (Fire Area)" },
        { code: "C6", name: "Secret Library (Ice Area)" },
        { code: "C7", name: "Secret Library (Energy Area)" },
        { code: "C8", name: "Secret Library (Earth Area)" },
        { code: "C9", name: "Secret Library (Biting Book)" }
      ]
    },
    {
      city: "Darashia",
      spawns: [
        { code: "D1", name: "Skeleton Elite Warrior (Inside)" },
        { code: "D2", name: "Skeleton Elite Warrior (Outside)" },
        { code: "D3", name: "Dragon" },
        { code: "D4", name: "Dragon Lord" },
        { code: "D5", name: "Drefia Grim Reaper (Floor 1)" },
        { code: "D6", name: "Drefia Grim Reaper (Floor 1+2)" },
        { code: "D7", name: "Drefia Grim Reaper (Floor All)" },
        { code: "D8", name: "Elder Wyrm" },
        { code: "D9", name: "Minotaur" },
        { code: "D10", name: "Necro Hellgate" },
        { code: "D11", name: "Rotworm (East)" },
        { code: "D12", name: "Rotworm (West)" },
        { code: "D13", name: "Vamp Hell" },
        { code: "D14", name: "Wyrm" },
        { code: "D15", name: "Terramite's Cave" },
        { code: "D16", name: "Nightmare Isles" },
        { code: "D17", name: "Cults & Lizards" },
        { code: "D18", name: "Ancient Scarab Tomb" },
        { code: "D19", name: "Ferumbra's Lair (Entrance)" },
        { code: "D20", name: "Ferumbra's Lair (South)" },
        { code: "D21", name: "Ferumbra's Plague Seal" },
        { code: "D22", name: "Ferumbra's DT Seal" },
        { code: "D23", name: "Ferumbra's Jugger Seal" },
        { code: "D24", name: "Ferumbra's Fury Seal" },
        { code: "D25", name: "Ferumbra's Undead Seal" },
        { code: "D26", name: "Ferumbra's Arc" },
        { code: "D27", name: "Ferumbra's Pumin" },
        { code: "D28", name: "Haunted Nexus (Darashia)" },
        { code: "D29", name: "Werehyena -1" },
        { code: "D30", name: "Werehyena -2" },
        { code: "D31", name: "Werelion -1" },
        { code: "D32", name: "Werelion -2" },
        { code: "D33", name: "Plagueseal -1" },
        { code: "D34", name: "Plagueseal -2" },
        { code: "D35", name: "Pumin -1" },
        { code: "D36", name: "Pumin -2" },
        { code: "D37", name: "Pumin -3" },
        { code: "D38", name: "Infernatil" },
        { code: "D39", name: "Infernatil +1" },
        { code: "D40", name: "Undead Seal -1" },
        { code: "D41", name: "Undead Seal -2" },
        { code: "D42", name: "Bazir Caminho" },
        { code: "D43", name: "Bazir Paredes" },
        { code: "D44", name: "DT Seal -1" },
        { code: "D45", name: "DT Seal -2" },
        { code: "D46", name: "Juggerseal -1" },
        { code: "D47", name: "Juggerseal -2" }
      ]
    },
    {
      city: "Edron",
      spawns: [
        { code: "E1", name: "Askarak Demon" },
        { code: "E2", name: "Bog Raider (Cave Earth Elemental)" },
        { code: "E3", name: "Bog Raider East (Hidden)" },
        { code: "E4", name: "Cyclopolis" },
        { code: "E5", name: "Cyclopolis Behemoths" },
        { code: "E6", name: "Demon (Demon Helmet Quest)" },
        { code: "E7", name: "Demon (New)" },
        { code: "E8", name: "Demon Forge" },
        { code: "E9", name: "Dragon Lair" },
        { code: "E10", name: "Earth Elemental" },
        { code: "E11", name: "Inquisition" },
        { code: "E12", name: "Servants (Mad Mage)" },
        { code: "E13", name: "Shaburak Demons" },
        { code: "E14", name: "Soil ED (Elemental Quest)" },
        { code: "E15", name: "Soil EK (Elemental Quest)" },
        { code: "E16", name: "Soil MS (Elemental Quest)" },
        { code: "E17", name: "Soil RP (Elemental Quest)" },
        { code: "E18", name: "Vampire Crypt" },
        { code: "E19", name: "Dryad Gardens" },
        { code: "E20", name: "Treeling Dungeon" },
        { code: "E21", name: "Forgotten Tomb" },
        { code: "E22", name: "Grimvale" },
        { code: "E23", name: "Werefox Cave" },
        { code: "E24", name: "Hero Fortress -1" },
        { code: "E25", name: "Hero Fortress -2" },
        { code: "E26", name: "Hero Fortress -3" },
        { code: "E27", name: "Hellhound Inquisitor" },
        { code: "E28", name: "Zugurosh" },
        { code: "E29", name: "Falcon Bastion" },
        { code: "E30", name: "Falcon (Underground)" },
        { code: "E31", name: "Falcon Mini-Bosses" },
        { code: "E32", name: "Flimsy -1" },
        { code: "E33", name: "Usurper East" },
        { code: "E34", name: "Bounac" },
        { code: "E35", name: "Ancient Lion Knight" },
        { code: "E36", name: "Crypt Warden" },
        { code: "E37", name: "Carnisylvan" }
      ]
    },
    {
      city: "Farmine",
      spawns: [
        { code: "F1", name: "Brimston Bug (Hidden)" },
        { code: "F2", name: "Brimston Bug (Shovel)" },
        { code: "F3", name: "Brimston Bug (Surface)" },
        { code: "F4", name: "Brimston Bug (Wrath)" },
        { code: "F5", name: "Corruption Hole -1" },
        { code: "F6", name: "Corruption Hole -2" },
        { code: "F7", name: "Dragon" },
        { code: "F8", name: "Dragonblaze" },
        { code: "F9", name: "Dragon Lord (Before TP)" },
        { code: "F10", name: "Dragon Lord (After TP)" },
        { code: "F11", name: "Draken Elite" },
        { code: "F12", name: "Draken Wall" },
        { code: "F13", name: "Draken Tower (Mid)" },
        { code: "F14", name: "Draken Wall (Top)" },
        { code: "F15", name: "Draken Wall (Bottom)" },
        { code: "F16", name: "Ghastly Dragon" },
        { code: "F17", name: "Ghastly Dragon (Mission 7)" },
        { code: "F18", name: "Ghastly Dragon (Mission 10)" },
        { code: "F19", name: "Ghastly Dragon (Palace)" },
        { code: "F20", name: "Hidden Lizards (Mission 7)" },
        { code: "F21", name: "Killer Caiman" },
        { code: "F22", name: "Lizard Camp (Muggy Plains)" },
        { code: "F23", name: "Lizard Chosen (New - 1,2,3)" },
        { code: "F24", name: "Lizard Chosen (New - 4,5)" },
        { code: "F25", name: "Lizard City" },
        { code: "F26", name: "Lizards (Mortal Combat)" },
        { code: "F27", name: "Souleaters" },
        { code: "F28", name: "Stampors" },
        { code: "F29", name: "Stone Golems" },
        { code: "F30", name: "Wailing Widow Cave" },
        { code: "F31", name: "Yielothax" },
        { code: "F32", name: "Flimsy -1" },
        { code: "F33", name: "Gold Token" }
      ]
    },
    {
      city: "Feyrist",
      spawns: [
        { code: "G1", name: "Fire Shrine" },
        { code: "G2", name: "Mini Roshamuul -1" },
        { code: "G3", name: "Mini Roshamuul -1 (West)" },
        { code: "G4", name: "Mini Roshamuul -1 (East)" },
        { code: "G5", name: "Mini Roshamuul -2" },
        { code: "G6", name: "Mini Roshamuul -2 (West)" },
        { code: "G7", name: "Mini Roshamuul -2 (East)" },
        { code: "G8", name: "Mini Roshamuul (All)" },
        { code: "G9", name: "Feyrist Surface Faes" },
        { code: "G10", name: "Feyrist Faun Cave" },
        { code: "G11", name: "Summer Court" },
        { code: "G12", name: "Winter Court" },
        { code: "G13", name: "Dream Laberynth (Fire)" },
        { code: "G14", name: "Dream Laberynth (Ice)" }
      ]
    },
    {
      city: "Forbidden Islands",
      spawns: [
        { code: "H1", name: "Behemoths" },
        { code: "H2", name: "Giant Spiders" },
        { code: "H3", name: "Hydras" }
      ]
    },
    {
        city: "Goroma",
        spawns: [
          { code: "I1", name: "Bonebeast" },
          { code: "I2", name: "Cults" },
          { code: "I3", name: "Demons" },
          { code: "I4", name: "Dragon Lair" },
          { code: "I5", name: "Ferumbras Tower" },
          { code: "I6", name: "Giant Spiders" },
          { code: "I7", name: "Hydras" },
          { code: "I8", name: "Lich Hell" },
          { code: "I9", name: "Quara Scout (GS Island)" },
          { code: "I10", name: "Quara Scout (Hydra Island)" },
          { code: "I11", name: "Medusa -1 (West) & West" },
          { code: "I12", name: "Medusa -1 (East)" },
          { code: "I13", name: "Medusa North & Northwest" },
          { code: "I14", name: "Medusa East & Northest" }
        ]
      },
      {
        city: "Gray Island",
        spawns: [
          { code: "J1", name: "Deepling (East)" },
          { code: "J2", name: "Deepling (North)" },
          { code: "J3", name: "Deepling (North - Hardcore)" },
          { code: "J4", name: "Deepling (South - Library)" },
          { code: "J5", name: "Deepling (West)" },
          { code: "J6", name: "Hive Surface" },
          { code: "J7", name: "Hive Tower" },
          { code: "J8", name: "Hive Tower (East - Stage 1)" },
          { code: "J9", name: "Hive Tower (Northeast - Stage 2)" },
          { code: "J10", name: "Hive Tower (West - Stage 3)" },
          { code: "J11", name: "Hive Underground" },
          { code: "J12", name: "Deathling (Port Hope)" },
          { code: "J13", name: "Deathling -1" },
          { code: "J14", name: "Deathling -2" }
        ]
      },
      {
        city: "Issavi",
        spawns: [
          { code: "K1", name: "Bridge (West)" },
          { code: "K2", name: "Desert (South)" },
          { code: "K3", name: "Sphinx Cave -1" },
          { code: "K4", name: "Sphinx Cave -2" },
          { code: "K5", name: "Underground (Sewers)" },
          { code: "K6", name: "Waterfall" },
          { code: "K7", name: "Pirat Ship" },
          { code: "K8", name: "Pirat -1" },
          { code: "K9", name: "Pirat -2" },
          { code: "K10", name: "Exotic Cave -1" },
          { code: "K11", name: "Exotic Cave -2" },
          { code: "K12", name: "Ruins of Nuur (Bilu)" },
          { code: "K13", name: "Salt Caves (Bashmu)" }
        ]
      },
      {
        city: "Kazordoon",
        spawns: [
          { code: "L1", name: "Corym" },
          { code: "L2", name: "Drillworms (East)" },
          { code: "L3", name: "Drillworms (West)" },
          { code: "L4", name: "Lost Dwarfs (East)" },
          { code: "L5", name: "Lost Dwarfs (Small Respawn)" },
          { code: "L6", name: "Lost Dwarfs (West)" },
          { code: "L7", name: "Lost Dwarfs (West Up)" },
          { code: "L8", name: "Lower Spikes" }
        ]
      },
      {
        city: "Krailos",
        spawns: [
          { code: "M1", name: "Brimstone Bugs" },
          { code: "M2", name: "Nightmare Krailos" }
        ]
      },
      {
        city: "Yalahar",
        spawns: [
          { code: "V1", name: "Arena Quarter" },
          { code: "V2", name: "Barbarian Bloodwalker" },
          { code: "V3", name: "Blue Djinn" },
          { code: "V4", name: "Bog Raider (North)" },
          { code: "V5", name: "Bog Raider + Nightmare + Destroyer" },
          { code: "V6", name: "Cemetery -1" },
          { code: "V7", name: "Cemetery Ghoul (East)" },
          { code: "V8", name: "Cemetery Ghoul (West)" },
          { code: "V9", name: "Cemetery Zombies" },
          { code: "V10", name: "Cults" },
          { code: "V11", name: "Cycs Mistrock (Center)" },
          { code: "V12", name: "Cycs Mistrock (North)" },
          { code: "V13", name: "Cycs Mistrock (South)" },
          { code: "V14", name: "Demon (East)" },
          { code: "V15", name: "Demon (West)" },
          { code: "V16", name: "Dragon Lord (Fenrock)" },
          { code: "V17", name: "Elfs" },
          { code: "V18", name: "Giant Spider" },
          { code: "V19", name: "Green Djinn" },
          { code: "V20", name: "Grim Reaper (East)" },
          { code: "V21", name: "Grim Reaper (West)" },
          { code: "V22", name: "Haunted Treeling" },
          { code: "V23", name: "Hellspawn (Surface)" },
          { code: "V24", name: "Hellspawn -1" },
          { code: "V25", name: "Magician" },
          { code: "V26", name: "Minotaurs" },
          { code: "V27", name: "Mutated Human" },
          { code: "V28", name: "Mutated Rat" },
          { code: "V29", name: "Necromancer (East)" },
          { code: "V30", name: "Necromancer (West)" },
          { code: "V31", name: "Nightmare" },
          { code: "V32", name: "Pirates" },
          { code: "V33", name: "Sunken Quaras" },
          { code: "V34", name: "Tortoise & Barbarian (Fenrock)" },
          { code: "V35", name: "Vengoth Castle" },
          { code: "V36", name: "Vengoth Castle (North)" },
          { code: "V37", name: "War Golem (New - East)" },
          { code: "V38", name: "War Golem (New - West)" },
          { code: "V39", name: "Werewolf" },
          { code: "V40", name: "Worker Golem" },
          { code: "V41", name: "Dragon (Hydra)" },
          { code: "V42", name: "Dragon (NW)" },
          { code: "V43", name: "Dragon (SE)" },
          { code: "V44", name: "Dragon (Serpent)" },
          { code: "V45", name: "Claustrophobic Inferno" },
          { code: "V46", name: "Rotten Wasteland (North)" },
          { code: "V47", name: "Rotten Wasteland (South)" },
          { code: "V48", name: "Ebb and Flow" },
          { code: "V49", name: "Furious Crater" },
          { code: "V50", name: "Mirrored Nightmare" }
        ]
      },
      {
        city: "Thais",
        spawns: [
          { code: "S1", name: "Mintwallin" },
          { code: "S2", name: "Minotaur Cult Cave -1" },
          { code: "S3", name: "Minotaur Cult Cave -2" },
          { code: "S4", name: "Thais Fury" }
        ]
      },
      {
        city: "Venore",
        spawns: [
          { code: "T1", name: "Dragon Lair (East)" },
          { code: "T2", name: "Dragon Lair (West)" },
          { code: "T3", name: "Dragon Lord (POI)" },
          { code: "T4", name: "Orc Fortress (Inside)" },
          { code: "T5", name: "Orc Fortress (Outside)" },
          { code: "T6", name: "Rorc" },
          { code: "T7", name: "Tainted Soul Cave" },
          { code: "T8", name: "Salamander" },
          { code: "T9", name: "Amazon Camp" },
          { code: "T10", name: "Dark Cathedral" },
          { code: "T11", name: "Buried Cathedral" },
          { code: "T12", name: "Haunted Nexus (POH)" },
          { code: "T13", name: "Flimsy -1" },
          { code: "T14", name: "Flimsy -2" },
          { code: "T15", name: "Flimsy -3" },
          { code: "T16", name: "Stonerefiner" }
        ]
      },
      {
        city: "Warzone",
        spawns: [
          { code: "U1", name: "Crystal Golems" },
          { code: "U2", name: "Crystal Grounds" },
          { code: "U3", name: "Gnomegate Hotspot" },
          { code: "U4", name: "Mushroom Gardens" },
          { code: "U5", name: "Warzone 3" },
          { code: "U6", name: "Warzone 4" },
          { code: "U7", name: "Warzone 4 (North)" },
          { code: "U8", name: "Warzone 4 (South)" },
          { code: "U9", name: "Warzone 5" },
          { code: "U10", name: "Warzone 5 (North)" },
          { code: "U11", name: "Warzone 5 (South)" },
          { code: "U12", name: "Warzone 6" },
          { code: "U13", name: "Warzone 6 (North)" },
          { code: "U14", name: "Warzone 6 (South)" },
          { code: "U15", name: "Warzone 7" },
          { code: "U16", name: "Warzone 7 -1" },
          { code: "U17", name: "Warzone 7 -2" },
          { code: "U18", name: "Warzone 8" },
          { code: "U19", name: "Warzone 9 (Upper)" },
          { code: "U20", name: "Warzone 9 (Lower)" },
          { code: "U21", name: "Diremaw (North)" },
          { code: "U22", name: "Diremaw (South)" }
        ]
      },
      {
        city: "Roshamuul",
        spawns: [
          { code: "Q1", name: "Bridge" },
          { code: "Q2", name: "Guzzlemaw Valley (Center)" },
          { code: "Q3", name: "Guzzlemaw Valley (East)" },
          { code: "Q4", name: "Guzzlemaw Valley (West)" },
          { code: "Q5", name: "Prison" },
          { code: "Q6", name: "Prison -1" },
          { code: "Q7", name: "Prison -2" },
          { code: "Q8", name: "Prison -3" },
          { code: "Q9", name: "Surface -3" },
          { code: "B24", name: "Rosha West (Bombra)" },
          { code: "Q10", name: "Surface (Buckets)" },
          { code: "Q11", name: "Surface (Buckets West)" },
          { code: "Q12", name: "Surface (Buckets East)" },
          { code: "Q13", name: "Roshamuul DP (North)" },
          { code: "Q14", name: "Roshamuul DP (South)" },
          { code: "Q15", name: "Choking Fear (DP Northeast)" },
          { code: "Q16", name: "Roshamuul Mountain East" },
          { code: "Q17", name: "Roshamuul Mountain North East" },
          { code: "Q18", name: "Roshamuul Mountain South" },
          { code: "Q19", name: "Shock Head" }
        ]
      },
      {
        city: "Svargrond",
        spawns: [
          { code: "R1", name: "Barbarian Camp (Big)" },
          { code: "R2", name: "Barbarian Camp (Medium)" },
          { code: "R3", name: "Barbarian Camp (Small)" },
          { code: "R4", name: "Crystal Spiders (Hidden)" },
          { code: "R5", name: "Crystal Spiders (New)" },
          { code: "R6", name: "Crystal Spiders (Nibelor)" },
          { code: "R7", name: "Crystal Spiders (Old)" },
          { code: "R8", name: "Crystal Spiders North (New)" },
          { code: "R9", name: "Crystal Spiders South (New)" },
          { code: "R10", name: "Cults Hidden" },
          { code: "R11", name: "Cults Mines (East)" },
          { code: "R12", name: "Cults Mines (North West)" },
          { code: "R13", name: "Frost Dragons East (Okolnir)" },
          { code: "R14", name: "Frost Dragons West (Okolnir)" },
          { code: "R15", name: "Frost Giant" },
          { code: "R16", name: "Hidden Formogar Mines" },
          { code: "R17", name: "Ice Witch Temple (New)" },
          { code: "R18", name: "Mammoth Factory" },
          { code: "R19", name: "Mines -2" },
          { code: "R20", name: "Mines -3" },
          { code: "R21", name: "Mines South East -2" },
          { code: "R22", name: "Mines Yakchal Floor" },
          { code: "R23", name: "Sea Serpent (New Cave)" },
          { code: "R24", name: "Sea Serpent -1 (New Cave)" },
          { code: "R25", name: "Sea Serpent North (Old Cave)" },
          { code: "R26", name: "Sea Serpent South (Old Cave)" },
          { code: "R27", name: "Gold Token" },
          { code: "R28", name: "Gold Token (Volta Farmine)" }
        ]
    },
    {
        city: "Liberty Bay",
        spawns: [
          { code: "N1", name: "Behemoths" },
          { code: "N2", name: "Cults" },
          { code: "N3", name: "Earth Elemental" },
          { code: "N4", name: "Laguna Island" },
          { code: "N5", name: "Night Stalker -1" },
          { code: "N6", name: "Pirate (Nargor)" },
          { code: "N7", name: "Quara East (Calassa)" },
          { code: "N8", name: "Quaras West (Calassa)" },
          { code: "N9", name: "Wyrms +1" },
          { code: "N10", name: "Wyrms +2" },
          { code: "N11", name: "Zombie (Treasure Island)" },
          { code: "N12", name: "Quara (New)" },
          { code: "N13", name: "Wyrms Cave (New)" },
          { code: "N14", name: "Coryms" },
          { code: "N15", name: "Hive Outpost" },
          { code: "N16", name: "Gargoyles (Meriana)" },
          { code: "N17", name: "Crystal Gardens" }
        ]
      }
]; 