  export const worlds = [
    { name: "Ambra", location: "South America", pvpType: "Retro Open PvP" },
    { name: "Antica", location: "Europe", pvpType: "Open PvP" },
    { name: "Astera", location: "North America", pvpType: "Optional PvP" },
    { name: "Belobra", location: "South America", pvpType: "Optional PvP" },
    { name: "Bona", location: "Europe", pvpType: "Optional PvP" },
    { name: "Calmera", location: "North America", pvpType: "Optional PvP" },
    { name: "Celebra", location: "South America", pvpType: "Optional PvP" },
    { name: "Celesta", location: "Europe", pvpType: "Optional PvP" },
    { name: "Collabra", location: "South America", pvpType: "Optional PvP" },
    { name: "Descubra", location: "South America", pvpType: "Optional PvP" },
    { name: "Dia", location: "Europe", pvpType: "Optional PvP" },
    { name: "Divina", location: "Europe", pvpType: "Retro Open PvP" },
    { name: "Epoca", location: "Europe", pvpType: "Retro Open PvP" },
    { name: "Esmera", location: "North America", pvpType: "Optional PvP" },
    { name: "Etebra", location: "South America", pvpType: "Optional PvP" },
    { name: "Ferobra", location: "South America", pvpType: "Open PvP" },
    { name: "Fibera", location: "North America", pvpType: "Retro Open PvP" },
    { name: "Firmera", location: "North America", pvpType: "Retro Open PvP" },
    { name: "Flamera", location: "North America", pvpType: "Retro Open PvP" },
    { name: "Gentebra", location: "South America", pvpType: "Optional PvP" },
    { name: "Gladera", location: "North America", pvpType: "Optional PvP" },
    { name: "Gladibra", location: "South America", pvpType: "Retro Open PvP" },
    { name: "Gravitera", location: "North America", pvpType: "Retro Hardcore PvP" },
    { name: "Harmonia", location: "Europe", pvpType: "Optional PvP" },
    { name: "Havera", location: "North America", pvpType: "Open PvP" },
    { name: "Honbra", location: "South America", pvpType: "Open PvP" },
    { name: "Inabra", location: "South America", pvpType: "Open PvP" },
    { name: "Issobra", location: "South America", pvpType: "Optional PvP" },
    { name: "Jacabra", location: "South America", pvpType: "Retro Hardcore PvP" },
    { name: "Jadebra", location: "South America", pvpType: "Open PvP" },
    { name: "Jaguna", location: "Europe", pvpType: "Open PvP" },
    { name: "Kalibra", location: "South America", pvpType: "Optional PvP" },
    { name: "Karmeya", location: "Europe", pvpType: "Optional PvP" },
    { name: "Lobera", location: "North America", pvpType: "Open PvP" },
    { name: "Luminera", location: "North America", pvpType: "Optional PvP" },
    { name: "Lutabra", location: "South America", pvpType: "Retro Open PvP" },
    { name: "Malivora", location: "Europe", pvpType: "Retro Open PvP" },
    { name: "Menera", location: "North America", pvpType: "Optional PvP" },
    { name: "Monza", location: "Europe", pvpType: "Optional PvP" },
    { name: "Nefera", location: "North America", pvpType: "Optional PvP" },
    { name: "Nevia", location: "Europe", pvpType: "Optional PvP" },
    { name: "Obscubra", location: "South America", pvpType: "Retro Hardcore PvP" },
    { name: "Oceanis", location: "Oceania", pvpType: "Optional PvP" },
    { name: "Ombra", location: "South America", pvpType: "Open PvP" },
    { name: "Ourobra", location: "South America", pvpType: "Open PvP" },
    { name: "Pacera", location: "North America", pvpType: "Optional PvP" },
    { name: "Peloria", location: "Europe", pvpType: "Open PvP" },
    { name: "Premia", location: "Europe", pvpType: "Open PvP" },
    { name: "Quebra", location: "South America", pvpType: "Retro Open PvP" },
    { name: "Quelibra", location: "South America", pvpType: "Open PvP" },
    { name: "Quidera", location: "North America", pvpType: "Open PvP" },
    { name: "Quintera", location: "North America", pvpType: "Open PvP" },
    { name: "Rasteibra", location: "South America", pvpType: "Open PvP" },
    { name: "Refugia", location: "Europe", pvpType: "Optional PvP" },
    { name: "Retalia", location: "Europe", pvpType: "Retro Hardcore PvP" },
    { name: "Runera", location: "North America", pvpType: "Open PvP" },
    { name: "Secura", location: "Europe", pvpType: "Optional PvP" },
    { name: "Serdebra", location: "South America", pvpType: "Open PvP" },
    { name: "Solidera", location: "North America", pvpType: "Open PvP" },
    { name: "Stralis", location: "Oceania", pvpType: "Optional PvP" },
    { name: "Talera", location: "North America", pvpType: "Open PvP" },
    { name: "Temera", location: "North America", pvpType: "Retro Open PvP" },
    { name: "Thyria", location: "Europe", pvpType: "Open PvP" },
    { name: "Tornabra", location: "South America", pvpType: "Open PvP" },
    { name: "Ulera", location: "North America", pvpType: "Optional PvP" },
    { name: "Unebra", location: "South America", pvpType: "Open PvP" },
    { name: "Ustebra", location: "South America", pvpType: "Optional PvP" },
    { name: "Vandera", location: "North America", pvpType: "Open PvP" },
    { name: "Venebra", location: "South America", pvpType: "Optional PvP" },
    { name: "Victoris", location: "Oceania", pvpType: "Open PvP" },
    { name: "Vitera", location: "North America", pvpType: "Optional PvP" },
    { name: "Vunira", location: "Europe", pvpType: "Open PvP" },
    { name: "Wadira", location: "Europe", pvpType: "Optional PvP" },
    { name: "Wildera", location: "North America", pvpType: "Retro Hardcore PvP" },
    { name: "Wintera", location: "North America", pvpType: "Open PvP" },
    { name: "Xyla", location: "Europe", pvpType: "Open PvP" },
    { name: "Yara", location: "Europe", pvpType: "Open PvP" },
    { name: "Yonabra", location: "South America", pvpType: "Optional PvP" },
    { name: "Yovera", location: "North America", pvpType: "Optional PvP" },
    { name: "Yubra", location: "South America", pvpType: "Optional PvP" },
    { name: "Zephyra", location: "Europe", pvpType: "Optional PvP" },
    { name: "Zuna", location: "Europe", pvpType: "Hardcore PvP" },
    { name: "Zunera", location: "North America", pvpType: "Hardcore PvP" }
  ];
  